version: '3.1'
networks:
  default:
    external: true
    name: FoodTruckFinder
services:

  MySQL:
    image: 'mysql/mysql-server:latest'
    container_name: FoodTruckDatabase
    environment:
      - MYSQL_DATABASE=food-truck-finder
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
  FrontEnd:
    build: './food-truck-frontend'
    image: 'food-truck-frontend'
    container_name: FoodTruckFrontend
    ports: 
      - 3000:3000
  API:
    build: './food-truck-api'
    image: 'food-truck-api'
    container_name: FoodTruckAPI
    restart: always
    ports:
      - 8090:8090
    environment:
      - spring.datasource.url=jdbc:mysql://MySQL:3306/food-truck-finder?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=password
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.session.store-type=jdbc
      - spring.session.jdbc.initialize-schema=always
      - spring.session.jdbc.table-name=SPRING_SESSION
